POST {{endpoint}}/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "{{username}}",
    "password": "{{password}}"
}

> {%
    client.global.set("token", jsonPath(response.body,"data.token"));
%}

###
GET {{endpoint}}/api/v1/santo
Content-Type: application/json
Authorization: Bearer {{token}}
###

###
GET {{endpoint}}/api/v1/santo/onomastico/Gianmaria
Content-Type: application/json
Authorization: Bearer {{token}}
###
